<?php

declare(strict_types=1);
const CYSE_HEADERS_VERSION='1.0.0';
function norm(array $h):array{$o=[];foreach($h as $k=>$v){if(is_int($k))continue;foreach(is_array($v)?$v:[$v] as $x)$o[strtolower(trim((string)$k))][]=trim((string)$x);}return $o;}
function hv(array $h,string $n):?string{$v=$h[strtolower($n)]??[];return $v?implode(', ',$v):null;}
function f(string $id,string $header,string $status,string $severity,?string $observed,string $rationale,string $recommendation,?string $limitations=null):array{return compact('id','header','status','severity','observed','rationale','recommendation','limitations')+['evidence'=>$observed===null?'header absent':"observed: $observed"];}
function evaluate(array $o):array{$h=$o['headers'];$https=strtolower((string)parse_url($o['final_url'],PHP_URL_SCHEME))==='https';$r=[];
$v=hv($h,'strict-transport-security');if(!$https)$r[]=f('hsts','Strict-Transport-Security','NOT_APPLICABLE','HIGH',$v,'HSTS is established by HTTPS responses.','Use HTTPS before evaluating HSTS.');elseif($v===null)$r[]=f('hsts','Strict-Transport-Security','FAIL','HIGH',null,'HTTPS lacks HSTS.','Add HSTS with a positive max-age.');elseif(preg_match('/max-age\s*=\s*0(?:\D|$)/i',$v))$r[]=f('hsts','Strict-Transport-Security','WEAK','HIGH',$v,'max-age=0 disables HSTS.','Use a justified positive max-age.');elseif(preg_match('/max-age\s*=\s*[1-9][0-9]*/i',$v))$r[]=f('hsts','Strict-Transport-Security','PASS','HIGH',$v,'A positive HSTS max-age is present.','Review optional directives separately.');else$r[]=f('hsts','Strict-Transport-Security','UNKNOWN','HIGH',$v,'The HSTS value cannot be interpreted defensibly.','Review its syntax.');
$v=hv($h,'content-security-policy');$r[]=$v===null?f('csp','Content-Security-Policy','FAIL','HIGH',null,'No CSP was observed.','Define an application-appropriate CSP.'):(trim($v)===''?f('csp','Content-Security-Policy','WEAK','HIGH',$v,'CSP is empty.','Define a non-empty CSP.'):f('csp','Content-Security-Policy','PASS','HIGH',$v,'A non-empty CSP was observed.','Review policy strength separately.','v1 does not fully analyze CSP strength.'));
$v=hv($h,'x-content-type-options');$r[]=$v===null?f('nosniff','X-Content-Type-Options','FAIL','MEDIUM',null,'MIME sniffing protection was not observed.','Set X-Content-Type-Options: nosniff.'):(strcasecmp(trim($v),'nosniff')===0?f('nosniff','X-Content-Type-Options','PASS','MEDIUM',$v,'nosniff is enabled.','Keep it enabled.'):f('nosniff','X-Content-Type-Options','WEAK','MEDIUM',$v,'The value does not enable nosniff.','Set nosniff.'));
$v=hv($h,'x-frame-options');$u=strtoupper(trim((string)$v));$r[]=$v===null?f('frame','X-Frame-Options','FAIL','MEDIUM',null,'Legacy frame protection was not observed.','Prefer CSP frame-ancestors; X-Frame-Options may remain defense in depth.','v1 does not fully parse frame-ancestors.'):(in_array($u,['DENY','SAMEORIGIN'],true)?f('frame','X-Frame-Options','PASS','MEDIUM',$v,'A recognized frame restriction is present.','Prefer CSP frame-ancestors as the modern mechanism.'):f('frame','X-Frame-Options','WEAK','MEDIUM',$v,'The value is not a supported restriction.','Use DENY/SAMEORIGIN or CSP frame-ancestors.'));
$v=hv($h,'referrer-policy');$lv=strtolower(trim((string)$v));$strong=['no-referrer','same-origin','strict-origin','strict-origin-when-cross-origin'];$weak=['unsafe-url','origin','origin-when-cross-origin','no-referrer-when-downgrade'];if($v===null)$r[]=f('referrer','Referrer-Policy','FAIL','LOW',null,'No explicit referrer policy was observed.','Set an explicit privacy-appropriate policy.');elseif(in_array($lv,$strong,true))$r[]=f('referrer','Referrer-Policy','PASS','LOW',$v,'Policy is in the v1 privacy-preserving set.','Confirm it matches application needs.');elseif($lv===''||in_array($lv,$weak,true))$r[]=f('referrer','Referrer-Policy','WEAK','LOW',$v,'Policy is empty or comparatively permissive.','Choose a stricter compatible policy.');else$r[]=f('referrer','Referrer-Policy','UNKNOWN','LOW',$v,'Policy is outside the bounded v1 table.','Review manually.');
$v=hv($h,'permissions-policy');$r[]=$v===null?f('permissions','Permissions-Policy','FAIL','LOW',null,'No Permissions-Policy was observed.','Define feature permissions.'):(trim($v)===''?f('permissions','Permissions-Policy','WEAK','LOW',$v,'Policy is empty.','Define explicit directives.'):f('permissions','Permissions-Policy','PASS','LOW',$v,'A non-empty policy was observed.','Review directives separately.','v1 does not audit directive strength.'));return $r;}
function observe(string $url,float $timeout,bool $follow):array{$ctx=stream_context_create(['http'=>['method'=>'GET','timeout'=>$timeout,'ignore_errors'=>true,'follow_location'=>$follow?1:0,'max_redirects'=>$follow?6:1,'user_agent'=>'CYSE-Headers/'.CYSE_HEADERS_VERSION],'ssl'=>['verify_peer'=>true,'verify_peer_name'=>true]]);$body=@file_get_contents($url,false,$ctx);$meta=$http_response_header??[];if($body===false&&$meta===[])throw new RuntimeException('network/observation failure');$blocks=[];$c=null;foreach($meta as $line){if(preg_match('#^HTTP/\S+\s+(\d{3})#i',$line,$m)){if($c)$blocks[]=$c;$c=['status'=>(int)$m[1],'headers'=>[]];}elseif($c!==null&&str_contains($line,':')){[$n,$v]=explode(':',$line,2);$c['headers'][trim($n)][]=trim($v);}}if($c)$blocks[]=$c;if(!$blocks)throw new RuntimeException('unsupported response condition');$last=end($blocks);return ['requested_url'=>$url,'final_url'=>$url,'status'=>$last['status'],'redirect_count'=>max(0,count($blocks)-1),'headers'=>norm($last['headers']),'warnings'=>[]];}
function aggregate(array $o):array{$fs=evaluate($o);$sc=[];$sev=[];foreach($fs as $x){$sc[$x['status']]=($sc[$x['status']]??0)+1;$sev[$x['severity']]=($sev[$x['severity']]??0)+1;}return ['schema_version'=>'1','tool_version'=>CYSE_HEADERS_VERSION]+$o+['findings'=>$fs,'status_counts'=>$sc,'severity_counts'=>$sev];}
function main(array $a):int{if(($a[1]??'')!=='audit'){fwrite(STDERR,"usage: cyse-headers audit <URL> [--timeout SECONDS] [--no-follow] [--json]\n");return 2;}$url=$a[2]??'';$json=in_array('--json',$a,true);$follow=!in_array('--no-follow',$a,true);$timeout=5.0;$i=array_search('--timeout',$a,true);if($i!==false){$x=$a[$i+1]??'';if(!is_numeric($x)||(float)$x<=0){fwrite(STDERR,"invalid timeout\n");return 2;}$timeout=(float)$x;}$scheme=strtolower((string)parse_url($url,PHP_URL_SCHEME));if(filter_var($url,FILTER_VALIDATE_URL)===false||!in_array($scheme,['http','https'],true)){fwrite(STDERR,"invalid absolute HTTP(S) URL\n");return 2;}try{$r=aggregate(observe($url,$timeout,$follow));}catch(Throwable $e){fwrite(STDERR,"observation error: {$e->getMessage()}\n");return 3;}if($json)echo json_encode($r,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n";else{echo "CYSE HTTP Security Headers Auditor\n{$r['requested_url']} [HTTP {$r['status']}]\n";foreach($r['findings'] as $x)echo sprintf("%-15s %-24s %s\n",$x['status'],$x['header'],$x['evidence']);echo 'Summary: ';foreach($r['status_counts'] as $k=>$v)echo "$k=$v ";echo "\n";}foreach($r['findings'] as $x)if($x['status']==='FAIL')return 1;return 0;}
if(realpath($_SERVER['SCRIPT_FILENAME']??'')===__FILE__)exit(main($argv));
